export const DIRECTIONS = {
    LEFT: 37,
    UP: 38,
    RIGHT: 39,
    DOWN: 40
}

export const SPEED = 50;
export const INITIAL_POSITION = { top: 100, left: 100 }
export const RERESH_RATE_MS = 1000;
export const BLOCK_DIAMETER = 50;

export const KEYCODES = {
    LEFT: 37,
    UP: 38,
    RIGHT: 39,
    DOWN: 40
}
export const INITIAL_BLOCKS_LENGTH = 10;

const { LEFT, RIGHT, UP, DOWN } = KEYCODES;
let DIRECTION_KEYCODE_MAP = {

};
DIRECTION_KEYCODE_MAP[LEFT] = DIRECTIONS.LEFT;
DIRECTION_KEYCODE_MAP[RIGHT] = DIRECTIONS.RIGHT;
DIRECTION_KEYCODE_MAP[UP] = DIRECTIONS.UP;
DIRECTION_KEYCODE_MAP[DOWN] = DIRECTIONS.DOWN;


export { DIRECTION_KEYCODE_MAP };